version: '3.7'

services:

  home-ui:
    container_name: home-ui
    build:
      context: ./frontend/home-ui
      dockerfile: Dockerfile
    restart: on-failure
    volumes:
      - ./frontend/home-ui/src:/usr/app/src
      - ./frontend/home-ui/public:/usr/app/public
    depends_on:
      nginx:
        condition: service_healthy
    stop_signal: SIGKILL
    stdin_open: true
    environment:
      HOME_UI_URL: $HOME_UI_URL
    tty: true
    ports:
      - '3000:3000'
    networks:
      wic_frontend:
        aliases: 
          - home-ui_ip

  links-api:
    ports:
      - 8000:8000

  mongo-db:
    volumes:
      - ./infra/mongo-db/data:/data/db
      - ./infra/mongo-db/log:/var/log/mongodb/
    ports:
      - 82:27017
  nginx:
    ports:
      - "81:80"
    volumes:
      - ./infra/nginx/log/:/var/log/nginx/log

volumes:
  mongo-data: {}
  nginx: {}
  home-ui: {}

networks: {}
